name:                reader-pattern-mig-app
version:             0.1.0.0
github:              "githubuser/reader-pattern-mig-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/reader-pattern-mig-app#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- deriving-aeson
- exceptions
- mtl
- stm
- time
- text
- containers
- mig

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingVia
  - DuplicateRecordFields
  - ConstraintKinds
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - OverloadedStrings
  - OverloadedRecordDot
  - RecordWildCards
  - TypeOperators

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -threaded

library:
  source-dirs: src

executables:
  reader-pattern-mig-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts "-with-rtsopts=-N -I0 -qg -A128m -n2m"
    dependencies:
    - immortal
    - optparse-applicative
    - yaml
    - reader-pattern-mig-app

tests:
  reader-pattern-mig-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reader-pattern-mig-app
